[package]
name = "jack_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
jack_ast = { path = "../jack_ast" }
vm_parser = { path = "../vm_parser" }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
